services:
  app:
    image: dn4
    container_name: dn4
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app