dataset_dir: dataset
data_name: default
mode: train
label_mode: make # ["make", "model", "color", "make_model", "make_model_color"]
outf: "runs/${hyps.run_name}"
resume: False
encoder_model: ResNet10
classifier_model: ProtoNet
workers: 0


imageSize: 224
train_aug: True
test_aug: True
episodeSize: 1
testepisodeSize: 1


# Important
epochs: 30
start_epoch: 1
current_epoch: -1
episode_train_num: 5000
episode_val_num: 500
episode_test_num: 500
way_num: 5
shot_num: 1
query_num: 15
aug_shot_num: 20
neighbor_k: 3

# Other parameters
lr: 0.05
cosine: True
lr_decay_epochs: [10, 20]
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9
adam: True
beta1: 0.5
cuda: True
ngpu: 1
nc: 3
clamp_lower: 0.01
clamp_upper: 0.01
print_freq: 100

experiment_name: fewshot_learning
run_name: ${..label_mode}_${hyps.encoder_model}_${hyps.classifier_model}_${hyps.imageSize}